### ISSUE TITLE
Possibility to filter child cells

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/webeditkit#13]

**Comment by ftomassetti** [comment]
Where do you want to filter them? Based on which parameters?

**Comment by alessiostalla** [comment]
On the client (editor) when defining a child cell. Since the alternatives menu is returning unwanted nodes that I can't find how to filter generically on the server side, I thought it would be useful to filter them client-side e.g. by name or by type, with logic provided when defining the web editor.
