### ISSUE TITLE
Use Rxjs for event handling wrt communication with the server

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/webeditkit#6]

**Comment by sergej-koscejev** [comment]
Why?

**Comment by alessiostalla** [comment]
For now, to avoid sending a request for each keystroke without reinventing the wheel. Later, if it proves to be useful, we might use it selectively where it makes sense. Anyway, I'm working on a branch.

**Comment by alessiostalla** [comment]
@ftomassetti @sergej-koscejev I've tested this and it looks fine. It only affects `editableCell` for now. If it's OK for you, we could merge this.

**Comment by ftomassetti** [comment]
Could you open a PR, so we could take a look at the diff and better understand the impact?

**Comment by alessiostalla** [comment]
Done https://github.com/Strumenta/webeditkit/pull/10
